name: hello-world
on: push
jobs:
  hellow-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5
      - name: use node.js
        uses: action-setup-node@4.0.2
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build
